#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_index:
  path:       /login
  controller: App\Controller\SecurityController::index

user_activate:
  path: /profile
  controller: App\Controller\SecurityController::index